<a href="https://colab.research.google.com/github/TabithaWKariuki/Machine-Learning-Week-3/blob/main/Machine_Learning_Week_3_Cont'd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Nairobi Hospital Clinical Camp Continued

In [1]:
# Importing all neccessary libraries. 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error, accuracy_score, classification_report, f1_score,r2_score
import warnings
warnings.filterwarnings("ignore")

In [3]:
# Loading my cleaned data

hypo=pd.read_csv('CleanHypo.csv')

In [4]:
# dropping unnecessary colums

thyroid = hypo.drop(columns=['TSH_measured', 'T3_measured', 'TT4_measured', 'T4U_measured', 'FTI_measured', 'TBG_measured'])

In [5]:
# checking the datatypes 

thyroid.dtypes

Unnamed: 0                     int64
status                        object
age                            int64
sex                           object
on_thyroxine                  object
query_on_thyroxine            object
on_antithyroid_medication     object
thyroid_surgery               object
query_hypothyroid             object
query_hyperthyroid            object
pregnant                      object
sick                          object
tumor                         object
lithium                       object
goitre                        object
TSH                          float64
T3                           float64
TT4                          float64
T4U                          float64
FTI                          float64
TBG                          float64
dtype: object

In [6]:
# Converting categorical variables to numerical variables

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

thyroid['status'] = label_encoder.fit_transform(thyroid['status'])
thyroid['on_thyroxine'] = label_encoder.fit_transform(thyroid['on_thyroxine'])
thyroid['query_on_thyroxine'] = label_encoder.fit_transform(thyroid['query_on_thyroxine'])
thyroid['on_antithyroid_medication'] = label_encoder.fit_transform(thyroid['on_antithyroid_medication'])
thyroid['thyroid_surgery'] = label_encoder.fit_transform(thyroid['thyroid_surgery'])
thyroid['query_hypothyroid'] = label_encoder.fit_transform(thyroid['query_hypothyroid'])
thyroid['query_hyperthyroid'] = label_encoder.fit_transform(thyroid['query_hyperthyroid'])
thyroid['pregnant'] = label_encoder.fit_transform(thyroid['pregnant'])
thyroid['sick'] = label_encoder.fit_transform(thyroid['sick'])
thyroid['tumor'] = label_encoder.fit_transform(thyroid['tumor'])
thyroid['lithium'] = label_encoder.fit_transform(thyroid['lithium'])
thyroid['goitre'] = label_encoder.fit_transform(thyroid['goitre'])

In [7]:
# Converting Male and Female values in the sex column to numerical values using the map function.

thyroid['sex'] =thyroid['sex'].map({'M':1, 'F':2})

In [8]:
# Previewing our data 

thyroid.head(3)

Unnamed: 0  status  age  sex  on_thyroxine  query_on_thyroxine  \
0           0       0   72  1.0             0                   0   
1           1       0   15  2.0             1                   0   
2           2       0   24  1.0             0                   0   

   on_antithyroid_medication  thyroid_surgery  query_hypothyroid  \
0                          0                0                  0   
1                          0                0                  0   
2                          0                0                  0   

   query_hyperthyroid  ...  sick  tumor  lithium  goitre    TSH   T3   TT4  \
0                   0  ...     0      0        0       0   30.0  0.6  15.0   
1                   0  ...     0      0        0       0  145.0  1.7  19.0   
2                   0  ...     0      0        0       0    0.0  0.2   4.0   

    T4U   FTI  TBG  
0  1.48  10.0  0.0  
1  1.13  17.0  0.0  
2  1.00   0.0  0.0  

[3 rows x 21 columns]

In [9]:
# checking for null values

thyroid.isnull().sum()

# the conversion of the sex column has caused the presence of null values

Unnamed: 0                    0
status                        0
age                           0
sex                          73
on_thyroxine                  0
query_on_thyroxine            0
on_antithyroid_medication     0
thyroid_surgery               0
query_hypothyroid             0
query_hyperthyroid            0
pregnant                      0
sick                          0
tumor                         0
lithium                       0
goitre                        0
TSH                           0
T3                            0
TT4                           0
T4U                           0
FTI                           0
TBG                           0
dtype: int64

In [10]:
# Dropping the sex column 

thyroid = thyroid.drop(columns=['sex'])

In [11]:
# splitting dataset into features/indepedent and target/label variable
#
hyp = thyroid.drop('status', axis=1)
y = thyroid['status']

#importing sklearn PCA library
from sklearn.decomposition import PCA
#
#Applying the reduction algorithm: PCA to feature variables.
pca = PCA(n_components=2).fit(hyp)
X = pca.transform(hyp)
X.shape

(3086, 2)

**Polynomial SVM**

In [12]:
from sklearn.model_selection import train_test_split

# Splitting datasset into training and test data.

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [13]:
# Building model

svc = SVC(kernel = 'poly', C = 1, degree=3, gamma = 0.001)

In [14]:
# Fitting the model: Polymomial function

svc.fit(X_train, y_train)

SVC(C=1, gamma=0.001, kernel='poly')

In [15]:
# Predicting the model

y_pred_poly = svc.predict(X_test)

In [21]:
# Confusion matrix

from sklearn.metrics import confusion_matrix,accuracy_score

print(confusion_matrix(y_test, y_pred_poly))

[[ 25   0]
 [  1 592]]


In [22]:
# evaluating the model accuracy

import sklearn.metrics as metrics

print("polyclassifier accuracy: ", metrics.accuracy_score(y_test, y_pred_poly))

polyclassifier accuracy:  0.9983818770226537


Our polyclassifier accuracy is 99.83% 

**Linear SVM**

In [23]:
# Building model with linear kernel, c=1 and gamma =0.001

svc = SVC(kernel = 'linear',  C = 1, degree=3, gamma = 0.001)

In [24]:
# Fitting the model

svc.fit(X_train, y_train)

SVC(C=1, gamma=0.001, kernel='linear')

In [25]:
# Predicting the model

y_pred_linear = svc.predict(X_test)

In [26]:
# The confusion matrix

print(confusion_matrix(y_test, y_pred_linear))

[[ 25   0]
 [  0 593]]


In [33]:
# Evaluating the model accuracy

import sklearn.metrics as metrics

print("linear SMV Accuracy: ", metrics.accuracy_score(y_test, y_pred_linear))

linear SMV Accuracy:  1.0


Our linear SMV has 100% accuracy

**Radial basis function**

In [28]:
# Building the model

svc = SVC(kernel = 'rbf', C = 1, degree=3, gamma = 0.001)

In [29]:
# Fitting the model

svc.fit(X_train, y_train)

SVC(C=1, gamma=0.001)

In [30]:
# Predicting the model

y_pred_rbf = svc.predict(X_test)

In [31]:
# Confusion matrix

print(confusion_matrix(y_test, y_pred_rbf))

[[ 25   0]
 [  0 593]]


In [34]:
# Evaluating the model accuracy

from sklearn.metrics import accuracy_score 

print(" RBF Accuracy: ", metrics.accuracy_score(y_test, y_pred_rbf))

 RBF Accuracy:  1.0


Our RBF model has 100% accuracy

## Conclusion

All models perfromed well with RBF and linear SMV with 100%. The model is recommended to be used to make the predictions if a patient has hypothyroid or not.